version: '3.9'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: my_qdrant
    restart: always
    ports:
      - "6333:6333"   # REST + gRPC API
      - "6334:6334"   # Web UI (можно открыть в браузере http://localhost:6334)
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
    name: ecommerce_postgres_data
  qdrant_data:
    name: ecommerce_qdrant_data
